
let moviesDB = [

{ 
  id:1,
  title:"joker",
  type:"movie",
  category:"action, drama, comedy",
  date:"2019",
  time:"1h 25min",
  quality:["fhd", "1080p"],
  rate:["10/7","5 stars"],
  desc:"The story of Disney's most iconic villain continues in The story of Disney's most iconic villain continues inThe story of Disney's most iconic villain continues inThe story of Disney's most iconic villain continues inThe story of Disney's most iconic villain continues inThe story of Disney's most iconic villain continues inThe story of Disney's most iconic villain continues inThe story of Disney's most iconic villain continues inThe story of Disney's most iconic villain continues inThe story of Disney's most iconic villain continues inThe story of Disney's most iconic villain continues inThe story of Disney's most iconic villain continues inThe story of Disney's most iconic villain The story of Disney's most iconic villain continues inThe story of Disney's most iconic villain continues inThe story of Disney's most iconic villain continues incontinues inThe story of Disney's most iconic villain continues inThe story of Disney's most iconic villain continues in",
  stars:"emily, the rock",
  director:"directorX, amin benz",
  writers:"lara croft",
  imageUrl:"./MOVIES-POSTERS/joker.jpg" 
},
{ 
  id:2,
  title:"jhon week",
  type:"movie",
  category:"action",
  date:"2017",
  time:"2h 25min",
  quality:["fhd", "1080p"],
  rate:"8/10",
  desc:"bla bla bla  bla bla blab  lab lablab la",
  stars:"emily, the rock",
  director:"directorX, amin benz",
  writers:"lara croft",
  imageUrl:"./MOVIES-POSTERS/jhonweek2.jpg" 
},
{ 
  id:3,
  title:"alladin",
  type:"movie",
  category:"drama, fantazy",
  date:"2019",
  time:"1h 25min",
  quality:["fhd", "1080p"],
  rate:"8/10",
  desc:"bla bla bla  bla bla blab  lab lablab la",
  stars:"emily, the rock",
  director:"directorX, amin benz ",
  writers:"lara croft",
  imageUrl:"./MOVIES-POSTERS/alladin.jpg" 
},
{ 
  id:4,
  title:"gravity",
  type:"movie",
  category:"sciFi, drama",
  date:"2019",
  time:"1h 25min",
  quality:["fhd", "1080p"],
  rate:"8/10",
  desc:"bla bla bla  bla bla blab  lab lablab la",
  stars:"emily, the rock",
  director:"directorX, amin benz ",
  writers:"lara croft",
  imageUrl:"./MOVIES-POSTERS/6gravity.jpg" 
},
{ 
  id:0,
  title:"mortal kombat",
  type:"movie",
  category:"action, adventure, aantasy",
  date:"2021",
  time:"1h 50min",
  quality:["fhd", "1080p","4k"],
  rate:["10/7","5 stars"],
  desc:"MMA fighter Cole Young seeks out Earth's greatest champions in order to stand against the enemies of Outworld in a high stakes battle for the universe.",
  stars:"Lewis Tan, Jessica McNamee, Josh Lawson",
  director:"Simon McQuoid",
  writers:"Greg Russo, Dave Callaham",
  imageUrl:"./MOVIES-POSTERS/mk.jpg" 
},
{ 
  id:5,
  title:"black panther",
  type:"movie",
  category:"action, heros",
  date:"2017",
  time:"1h 25min",
  quality:["fhd", "1080p"],
  rate:"8/10",
  desc:"bla bla bla  bla bla blab  lab lablab la",
  stars:"emily, the rock",
  director:"directorX, amin benz ",
  writers:"lara croft",
  imageUrl:"./MOVIES-POSTERS/5blackpanther.jpg" 
},
{ 
  id:6,
  title:"robbin hood",
  type:"movie",
  category:"romance",
  date:"2016",
  time:"1h 25min",
  quality:["fhd", "1080p"],
  rate:"8/10",
  desc:"bla bla bla  bla bla blab  lab lablab la",
  stars:"emily, the rock",
  director:"directorX, amin benz ",
  writers:"lara croft",
  imageUrl:"./MOVIES-POSTERS/4robinhood.jpeg" 
},
{ 
  id:7,
  title:"arrival",
  type:"movie",
  category:"drama, romace",
  date:"2019",
  time:"1h 25min",
  quality:["fhd", "1080p"],
  rate:"8/10",
  desc:"bla bla bla  bla bla blab  lab lablab la",
  stars:"emily, the rock",
  director:"directorX, amin benz ",
  writers:"lara croft",
  imageUrl:"./MOVIES-POSTERS/7arrival.jpg" 
},
{ 
  id:14,
  title:"How to Trai",
  type:"movie",
  category:"Animation, Action, Adventure",
  date:"2010",
  time:"98 Minutes",
  quality:["fhd", "1080p"],
  rate:"8.1/10",
  desc:"This film rolls fire-breathing action, epic adventure and big laughs into a captivating, fun and original story. Hiccup is a young Viking who defies tradition and befriends one of his deadliest foes - a ferocious dragon he calls Toothless. Together, the unlikely heroes fight against the odds to save both their worlds in this wonderful, feel-good hit.",
  stars:"Jay Baruchel, Gerard Butler, Christopher Mintz-Plasseemily",
  director:"Dean DeBlois, Chris Sanders",
  writers:"William Davies, Dean DeBlois ",
  imageUrl:"./MOVIES-POSTERS/How to Train Your Dragon.jpg" 
},
{ 
  id:8,
  title:"paracite",
  type:"movie",
  category:"action, drama",
  date:"2013",
  time:"1h 15min",
  quality:["fhd", "1080p"],
  rate:"8/10",
  desc:"bla bla bla  bla bla blab  lab lablab la",
  stars:"emily, the rock",
  director:"directorX, amin benz ",
  writers:"lara croft",
  imageUrl:"./MOVIES-POSTERS/8parasite.jpg" 
},
{ 
  id:9,
  title:"avengers",
  type:"movie",
  category:"action, fantasy",
  date:"2018",
  time:"1h 25min",
  quality:["4k", "2040p"],
  desc:"bla bla bla  bla bla blab  lab lablab la",
  stars:"emily, the rock",
  director:"directorX, amin benz ",
  writers:"lara croft",
  imageUrl:"./MOVIES-POSTERS/9avengers.jpg" 
},
{ 
  id:10,
  title:"harry poter",
  type:"movie",
  category:"fantasy, drama",
  date:"2019",
  time:"1h 25min",
  quality:["fhd", "1080p"],
  desc:"bla bla bla  bla bla blab  lab lablab la",
  stars:"emily, the rock",
  director:"directorX, amin benz ",
  writers:"lara croft",
  imageUrl:"./MOVIES-POSTERS/10harrypotter.jpg" 
},
{ 
  id:11,
  title:"lader raner",
  type:"movie",
  category:"action, racer",
  date:"2019",
  time:"1h 56min",
  quality:["fhd", "1080p"],
  desc:"bla bla bla  bla bla blab  lab lablab la",
  stars:"emily, the rock",
  director:"directorX, amin benz ",
  writers:"lara croft",
  imageUrl:"./MOVIES-POSTERS/11bladerunner.jpg" 
},
{ 
  id:12,
  title:"shutter island",
  type:"movie",
  category:"thiller, horror",
  date:"2002",
  time:"1h 25min",
  quality:["fhd", "1080p"],
  desc:"bla bla bla  bla bla blab  lab lablab la",
  stars:"emily, the rock",
  director:"directorX, amin benz ",
  writers:"lara croft",
  imageUrl:"./MOVIES-POSTERS/12shutterisland.jpg" 
},
{ 
  id:13,
  title:"free all",
  type:"movie",
  category:" drama, crime",
  date:"2009",
  time:"1h 25min",
  quality:["fhd", "1080p"],
  desc:"bla bla bla  bla bla blab  lab lablab la",
  stars:"emily, the rock",
  director:"directorX, amin benz ",
  writers:"lara croft",
  imageUrl:"./MOVIES-POSTERS/13freeall.jpg" 
},
{ 
  id:14,
  title:"star wars",
  type:"movie",
  category:"action, fantasy",
  date:"2019",
  time:"1h 25min",
  quality:["4K", "1080p"],
  desc:"bla bla bla  bla bla blab  lab lablab la",
  stars:"emily, the rock",
  director:"directorX, amin benz ",
  writers:"lara croft",
  imageUrl:"./MOVIES-POSTERS/14starwars.jpg" 
},
    
  ];

  localStorage.setItem("movies" , JSON.stringify(moviesDB));
  
